# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-02 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_images', models.ImageField(upload_to='images/gallery')),
                ('discription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishan.Discription')),
            ],
        ),
    ]
