# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-06 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishan', '0005_auto_20171007_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
