# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishan', '0008_auto_20171013_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='l',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField( max_length=254 ,blank='False',null='False',default='null'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(blank='False',null='False'),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField( max_length=100,blank='False',null='False'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField( max_length=100,blank='False',null='False'),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField( max_length=20000,blank='False',null='False'),
        ),
    ]
