# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishan', '0011_auto_20171013_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(max_length=254, null='false'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(null='false'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100, null='false'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, null='false'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=20000, null='false'),
        ),
    ]
