# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishan', '0016_auto_20171013_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_email',
        ),
    ]
