# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishan', '0017_remove_contact_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_no',
            field=models.IntegerField(default='10', null='False'),
        ),
    ]
